env:
  node: true
  es2021: true
extends: airbnb-base
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: 
  linebreak-style: ['error', 'unix']
  no-console: 0
  import/extensions:
    - error
    - ignorePackages
    - js: always
  import/no-extraneous-dependencies: 0
